# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190905_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeitem',
            name='in_number_list',
            field=models.BooleanField(default=True, verbose_name='участвует в нумерации курса'),
        ),
    ]
