# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20191117_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcourse',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_courses', to='groups.Group'),
        ),
    ]
