# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-09 08:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import project.training.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
        ('langs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, null=True, verbose_name='Ввод')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Редактор')),
                ('show_input', models.BooleanField(default=False, verbose_name='Отображать ввод')),
                ('show_debug', models.BooleanField(default=True, verbose_name='Отображать отладчик')),
                ('readonly', models.BooleanField(default=False, verbose_name='Только для чтения')),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ace', 'код'), ('text', 'текст')], default='text', max_length=255, verbose_name='тип')),
                ('order_key', project.training.fields.OrderField(blank=True, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'блок контента',
                'verbose_name_plural': 'блоки контента',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('about', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='краткое описание')),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='содержимое')),
                ('order_key', project.training.fields.OrderField(blank=True, verbose_name='порядок')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs.Lang', verbose_name='язык программирования')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('0', 'нет попыток'), ('1', 'нет прогресса'), ('2', 'есть прогресс'), ('3', 'решено')], default='0', max_length=255, verbose_name='статус')),
                ('progress', models.PositiveIntegerField(blank=True, default=0, verbose_name='Прогресс решения')),
                ('last_changes', models.CharField(blank=True, default='', max_length=255, verbose_name='последние изменения')),
                ('version_best', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='лучшее решение')),
                ('version_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='список сохраненных решений')),
            ],
            options={
                'verbose_name': 'решение задачи',
                'verbose_name_plural': 'решения задач',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='слаг')),
                ('order_key', project.training.fields.OrderField(blank=True, verbose_name='порядок')),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tasks.Task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='отображать')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, verbose_name='слаг')),
                ('order_key', project.training.fields.OrderField(blank=True, verbose_name='порядок')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_topics', to='training.Course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
                'ordering': ['order_key'],
            },
        ),
        migrations.AddField(
            model_name='taskitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_taskitems', to='training.Topic', verbose_name='тема'),
        ),
        migrations.AddField(
            model_name='solution',
            name='taskitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_solution', to='training.TaskItem', verbose_name='задача'),
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_content', to='training.Topic'),
        ),
    ]
