# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 15:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='последние изменения')),
                ('best', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='лучшее решение')),
                ('versions', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='сохраненные решения')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'решение задачи',
                'verbose_name_plural': 'решения задач',
            },
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='order_key',
            field=models.PositiveIntegerField(default=1, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskitems', to='training.Topic', verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order_key',
            field=models.PositiveIntegerField(default=1, verbose_name='порядок'),
        ),
        migrations.AddField(
            model_name='tasksolution',
            name='taskitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.TaskItem', verbose_name='задача'),
        ),
        migrations.AddField(
            model_name='tasksolution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
