# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 15:12
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_bottom',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='текстовый контент под списком тем'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='текстовый контент'),
        ),
    ]
