# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20191016_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='show',
            field=models.BooleanField(default=False, verbose_name='отображать'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_taskitems', to='training.Topic', verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_topics', to='training.Course', verbose_name='курс'),
        ),
    ]
