# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-12 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20191111_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='last_changes',
            field=models.TextField(blank=True, default='', verbose_name='последние изменения'),
        ),
    ]
