# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 17:33
from __future__ import unicode_literals

from django.db import migrations
import project.training.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20191112_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='url',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='number',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='url',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='url',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='slug',
            field=project.training.fields.SlugField(blank=True, default=1, max_length=255, verbose_name='слаг'),
            preserve_default=False,
        ),
    ]
