# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 08:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20191017_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksolution',
            name='taskitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_solution', to='training.TaskItem', verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='tasksolution',
            name='versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='сохраненные решения'),
        ),
    ]
