# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20191116_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order_key'], 'verbose_name': 'учебный курс', 'verbose_name_plural': 'учебные курсы'},
        ),
    ]
