# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20191019_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskSolution',
            new_name='Solution',
        ),
    ]
