# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 07:26
from __future__ import unicode_literals

from django.db import migrations
import project.training.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20191117_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='slug',
            field=project.training.fields.SlugField(blank=True, max_length=255, null=True, verbose_name='слаг'),
        ),
    ]
