# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20191020_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='show',
            field=models.BooleanField(default=True, verbose_name='отображать'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='show',
            field=models.BooleanField(default=True, verbose_name='отображать'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='show',
            field=models.BooleanField(default=True, verbose_name='отображать'),
        ),
    ]
