# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20191120_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='progress',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прогресс решения'),
        ),
    ]
