# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20191031_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ace', models.TextField()),
                ('text', tinymce.models.HTMLField()),
                ('type', models.CharField(choices=[('ace', 'ace'), ('text', 'text')], max_length=255)),
                ('order_key', models.PositiveIntegerField(blank=True, null=True, verbose_name='порядок')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_contents', to='training.Topic')),
            ],
            options={
                'verbose_name': 'контент',
                'verbose_name_plural': 'контент',
                'ordering': ('order_key',),
            },
        ),
    ]
