# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
