# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20191031_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('order_key',), 'verbose_name': 'блок контента', 'verbose_name_plural': 'блоки контента'},
        ),
        migrations.RenameField(
            model_name='content',
            old_name='ace',
            new_name='ace_content',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='ace_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='training.Topic'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('ace', 'код'), ('text', ' текст')], default='text', max_length=255, verbose_name='тип'),
        ),
    ]
