# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20191103_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='ace_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='ace_input',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='ace_show_input',
            new_name='show_input',
        ),
    ]
