# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20191105_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='readonly',
            field=models.BooleanField(default=False, verbose_name='Только для чтения'),
        ),
        migrations.AddField(
            model_name='content',
            name='show_debug',
            field=models.BooleanField(default=True, verbose_name='Отображать отладчик'),
        ),
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_content', to='training.Topic'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('ace', 'код'), ('text', 'текст')], default='text', max_length=255, verbose_name='тип'),
        ),
    ]
