# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190921_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('order_key',), 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('order_key',), 'verbose_name': 'источник материалов', 'verbose_name_plural': 'источники материалов'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('order_key',), 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('order_key',), 'verbose_name': 'тема', 'verbose_name_plural': 'темы'},
        ),
        migrations.AddField(
            model_name='source',
            name='order_key',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AddField(
            model_name='task',
            name='order_key',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
    ]
