# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-21 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190921_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='topic',
        ),
    ]
