# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20190921_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'ordering': ('order_key',)},
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='book.Course', verbose_name='курс'),
        ),
    ]
