# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
