# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lang',
            name='title',
        ),
        migrations.AddField(
            model_name='lang',
            name='provider',
            field=models.CharField(choices=[('python36', 'Python 3.6'), ('cpp', 'C++'), ('ch', 'C#')], default=2, max_length=255, unique=True, verbose_name='заголовок'),
            preserve_default=False,
        ),
    ]
